//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel;
    public partial class Suppliers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Suppliers()
        {
            this.Products = new HashSet<Products>();
        }

        [DisplayName("供應商編號")]
        public int SupplierID { get; set; }

        [Required]
        [DisplayName("公司名稱")]
        public string CompanyName { get; set; }

        [Required(ErrorMessage ="請填寫聯絡人資訊")]
        [DisplayName("聯絡人")]
        public string ContactName { get; set; }

        [Required(ErrorMessage = "請填寫聯絡人職稱")]
        [DisplayName("聯絡人職稱")]
        public string ContactTitle { get; set; }

        [Required(ErrorMessage = "請填地址")]
        [DisplayName("地址")]
        public string Address { get; set; }

        [Required(ErrorMessage = "請填寫城市")]
        [DisplayName("城市")]
        public string City { get; set; }

        [DisplayName("區域")]
        public string Region { get; set; }

        [Required(ErrorMessage = "請填寫郵遞區號")]
        [DisplayName("郵遞區號")]
        public string PostalCode { get; set; }

        [Required(ErrorMessage = "請填寫國家")]
        [DisplayName("國家")]
        public string Country { get; set; }

        [Required(ErrorMessage = "請填寫聯絡電話")]
        [DisplayName("電話")]
        public string Phone { get; set; }

        [DisplayName("傳真")]
        public string Fax { get; set; }

        [DisplayName("官方網站")]
        public string HomePage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Products> Products { get; set; }
    }
}
